name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mp4-to-mcap/**'  # Only trigger when files in this folder change
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mp4-to-mcap/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable mxschmitt/action-tmate' # Check out https://github.com/marketplace/actions/debugging-with-tmate
        required: false
        default: false

env:
  VERSION: 1.0.0  # Fixed version, update manually when needed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: coscene.cn:codemo
            registry: cr.coscene.cn
            image_name: codemo/mp4-to-mcap

    environment: ${{ matrix.environment }}
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: mp4-to-mcap  # Set working directory for all run steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ matrix.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.COSCENE_DOCKER_USER }}
          password: ${{ secrets.COSCENE_DOCKER_PASS }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.registry }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest
            type=sha,format=short
      
      - name: build-push-docker-image
        uses: docker/build-push-action@v6.11.0
        with:
          context: mp4-to-mcap
          platforms: linux/amd64
          push: false # ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      # use the ssh command in the output to connect to the tmate session and then run the following command to build the docker image:
      #   docker buildx build \
      #     --platform linux/amd64 \
      #     $(echo "${{ steps.meta.outputs.tags }}" | sed 's/^/-t /g') \
      #     $(echo "${{ steps.meta.outputs.labels }}" | sed 's/^/--label /g') \
      #     --push .
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ steps.meta.outputs.tags }}" | while read -r tag; do
            docker push "$tag"
          done
  